// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAccountRequest) Reset()         { *m = CheckAccountRequest{} }
func (m *CheckAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAccountRequest) ProtoMessage()    {}
func (*CheckAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *CheckAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccountRequest.Unmarshal(m, b)
}
func (m *CheckAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccountRequest.Marshal(b, m, deterministic)
}
func (m *CheckAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccountRequest.Merge(m, src)
}
func (m *CheckAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAccountRequest.Size(m)
}
func (m *CheckAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccountRequest proto.InternalMessageInfo

func (m *CheckAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CheckAccountReply struct {
	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chain      string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	AccountKey []byte `protobuf:"bytes,3,opt,name=accountKey,proto3" json:"accountKey,omitempty"`
	// TODO: Should use Coin message
	Balance              string   `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAccountReply) Reset()         { *m = CheckAccountReply{} }
func (m *CheckAccountReply) String() string { return proto.CompactTextString(m) }
func (*CheckAccountReply) ProtoMessage()    {}
func (*CheckAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *CheckAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccountReply.Unmarshal(m, b)
}
func (m *CheckAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccountReply.Marshal(b, m, deterministic)
}
func (m *CheckAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccountReply.Merge(m, src)
}
func (m *CheckAccountReply) XXX_Size() int {
	return xxx_messageInfo_CheckAccountReply.Size(m)
}
func (m *CheckAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccountReply proto.InternalMessageInfo

func (m *CheckAccountReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckAccountReply) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *CheckAccountReply) GetAccountKey() []byte {
	if m != nil {
		return m.AccountKey
	}
	return nil
}

func (m *CheckAccountReply) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

// Custom empty message in case we want to add new parameters in the future
type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{3}
}

func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (m *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(m, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*CheckAccountRequest)(nil), "pb.CheckAccountRequest")
	proto.RegisterType((*CheckAccountReply)(nil), "pb.CheckAccountReply")
	proto.RegisterType((*StatusRequest)(nil), "pb.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "pb.StatusReply")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x69, 0x76, 0x5d, 0x75, 0x5c, 0x5d, 0x76, 0x54, 0x0c, 0x0b, 0x4a, 0xc9, 0xa9, 0x82,
	0xf4, 0xa0, 0x77, 0x41, 0xf4, 0xd6, 0x5b, 0xfa, 0x04, 0x49, 0x08, 0x54, 0x5a, 0x93, 0x68, 0x52,
	0xa4, 0x6f, 0x2f, 0x4d, 0x2d, 0xb4, 0x6c, 0x6f, 0x99, 0x2f, 0xdf, 0x0c, 0xff, 0x0c, 0x80, 0x14,
	0x5e, 0xe7, 0xee, 0xc7, 0x06, 0x8b, 0xc4, 0x49, 0xf6, 0x08, 0xd7, 0xef, 0x95, 0x56, 0xf5, 0x9b,
	0x52, 0xb6, 0x35, 0x81, 0xeb, 0xef, 0x56, 0xfb, 0x80, 0x08, 0x6b, 0x23, 0xbe, 0x34, 0x4d, 0xd2,
	0x24, 0x3b, 0xe7, 0xf1, 0xcd, 0x7e, 0x61, 0x3f, 0x57, 0x5d, 0xd3, 0x2d, 0x89, 0x78, 0x03, 0x27,
	0xaa, 0x12, 0x9f, 0x86, 0x92, 0x08, 0x87, 0x02, 0x1f, 0x00, 0xc4, 0xd0, 0x59, 0xe8, 0x8e, 0xae,
	0xd2, 0x24, 0xdb, 0xf2, 0x09, 0x41, 0x0a, 0xa7, 0x52, 0x34, 0xc2, 0x28, 0x4d, 0xd7, 0xb1, 0x6f,
	0x2c, 0xd9, 0x0e, 0x2e, 0xcb, 0x20, 0x42, 0xeb, 0xff, 0xd3, 0xb1, 0x7b, 0xb8, 0x18, 0x41, 0x9f,
	0xe1, 0x0a, 0x88, 0xad, 0x63, 0x82, 0x33, 0x4e, 0x6c, 0xfd, 0xec, 0x61, 0x55, 0x7e, 0x14, 0xf8,
	0x04, 0x9b, 0xc1, 0xc2, 0x7d, 0xee, 0x64, 0x3e, 0x1b, 0x71, 0xd8, 0x4d, 0x51, 0x3f, 0xe4, 0x15,
	0xb6, 0xd3, 0xed, 0xf0, 0xae, 0x17, 0x16, 0x4e, 0x73, 0xb8, 0x3d, 0xfe, 0x70, 0x4d, 0x27, 0x37,
	0xf1, 0xa6, 0x2f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xdb, 0xc0, 0x47, 0x61, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SDKClient is the client API for SDK service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SDKClient interface {
	// Simple health-check to see if the server is OK
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountReply, error)
}

type sDKClient struct {
	cc *grpc.ClientConn
}

func NewSDKClient(cc *grpc.ClientConn) SDKClient {
	return &sDKClient{cc}
}

func (c *sDKClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/pb.SDK/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDKClient) CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountReply, error) {
	out := new(CheckAccountReply)
	err := c.cc.Invoke(ctx, "/pb.SDK/CheckAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SDKServer is the server API for SDK service.
type SDKServer interface {
	// Simple health-check to see if the server is OK
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	CheckAccount(context.Context, *CheckAccountRequest) (*CheckAccountReply, error)
}

func RegisterSDKServer(s *grpc.Server, srv SDKServer) {
	s.RegisterService(&_SDK_serviceDesc, srv)
}

func _SDK_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDKServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SDK/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDKServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDK_CheckAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDKServer).CheckAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SDK/CheckAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDKServer).CheckAccount(ctx, req.(*CheckAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SDK_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SDK",
	HandlerType: (*SDKServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _SDK_Status_Handler,
		},
		{
			MethodName: "CheckAccount",
			Handler:    _SDK_CheckAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base.proto",
}
