#!/usr/bin/env bash

chronos=$OLROOT/protocol/DOCKER/chronos
cp $chronos/config.toml $OLDATA
cp $chronos/genesis.json $OLDATA

olfullnode init --dir $OLDATA --genesis genesis.json --root $OLDATA --tendermintRoot --$OLDATA/consensus
