#!/bin/sh

if [ -z "$1" ]; then
	export NODENAME="OneLedger-Admin"
else
	export NODENAME=`echo $1 | awk -F# '{ print $1 }'`
fi

export CMD=$OLSCRIPT

export WORK=$OLDATA/$NODENAME
export LOG=$WORK
export DATA=$WORK/tendermint

pushd $WORK > /dev/null

tendermint show_node_id --home $DATA

popd > /dev/null
