#!/bin/bash

if [ -z "$1" ]; then
	nodeName="David-Node"
else
	nodeName=`echo $1 | awk -F# '{ print $1 }'`
fi

CMD=$OLSCRIPT

WORK=$OLDATA/$nodeName
LOG=$WORK
DATA=$WORK/consensus

pushd $WORK > /dev/null

tendermint show_node_id --home $DATA

popd > /dev/null
