#!/bin/bash

#
# TMUX script to monitor a node in the chain
#
SESSION=OneLedger-Node
TMUX=tmux 
# TMUX=tmux -CC # MacOS integration?

$TMUX -2 new-session -d -s $SESSION

# Setup a window for tailing log files
$TMUX new-window -t $SESSION:1 -n 'Tendermint'

$TMUX split-window -v -p 60
$TMUX split-window -v -p 50

$TMUX select-pane -t 0
$TMUX send-keys "pushd $OLDATA; tail -f tendermint.log" C-m

$TMUX select-pane -t 1
$TMUX send-keys "pushd $OLDATA; tail -f fullnode.log" C-m

$TMUX select-pane -t 2

# Set default window
$TMUX select-window -t $SESSION:1

# Attach to session
$TMUX -2 attach-session -t $SESSION

