#!/bin/bash

#
# TMUX script to monitor a node in the chain
#
SESSION=OneLedger-Node

tmux -2 new-session -d -s $SESSION

# Setup a window for tailing log files
tmux new-window -t $SESSION:1 -n 'Tendermint'

tmux split-window -v -p 60
tmux split-window -v -p 50

tmux select-pane -t 0
tmux send-keys "pushd $OLDATA; tail -f tendermint.log" C-m

tmux select-pane -t 1
tmux send-keys "pushd $OLDATA; tail -f fullnode.log" C-m

tmux select-pane -t 2

# Set default window
tmux select-window -t $SESSION:1

# Attach to session
tmux -2 attach-session -t $SESSION

