#!/bin/bash
#
# Move the sequence ids forward for testing, so that similar queries don't get caught in reply protection


export CMD=$OLSCRIPT

# Get the next seqeunce
if [ ! -f $CMD/sequence ]
then
    echo "101" > $CMD/sequence
fi

VAL=`cat $CMD/sequence`

# output it
echo "$VAL"

# Increment it
VAL=$(($VAL + 1))

# Overwrite the file wit the next one
echo $VAL > $CMD/sequence

