#!/bin/sh
#
# Clear out all of the chains: ours, geth and bitcoin
#

set -eu

#
# Setup the paths
#
export WORK=$GOPATH/test
export LOG=$GOPATH/test
export DATA=$GOPATH/data

# Control the working directory
pushd $WORK

#
# Cleanout any of the old database files
#

#
# Reset the main tendermint chain
#
tendermint unsafe_reset_all > $LOG/tendermint_init.log
tendermint init > $LOG/tendermint_init.log

#
# Reset our chain
#
fullnode unsafe_reset_all > $LOG/fullnode_init.log
fullnode init > $LOG/fullnode_init.log

#
# Reset Etheruem's chain
#

#
# Reset the Bitcoin chain
#

popd

