#!/bin/bash
#
# Reset our chain, remove any extra files and databases
#


if [ -z "$1" ]; then
	NODECOUNT=4
else
	NODECOUNT="$1"
fi

#
# Startup a bunch of nodes to act as a full block chain instance
#
export CMD=$OLSCRIPT
export STAGING=$OLDATA/staging

mkdir -p $STAGING

#
# Generate the overall genesis and validator information
#
tendermint testnet --home $STAGING --dir $STAGING --n $NODECOUNT

# TODO: Set the chain name, and set an initial amount of tokens and that admin owns them all

nodes="Admin-Node#mach0 Alice-Node#mach1 Bob-Node#mach2 Carol-Node#mach3"

for node in $nodes
do
	$CMD/resetNode $node $STAGING 
done

