#!/bin/bash
#
# Reset our chain, remove any extra files and databases
#

# TODO: Set this up to not copy if subdir is empty
if [ -z "$1" ]; then
	export NODENAME="OneLedger-David"
	export SUBDIR="mach0"
	export STAGING=$OLDATA/staging
else
 	export NODENAME="$1"
	export SUBDIR="$1"
	export STAGING="$2"
fi

echo "Resetting $NODENAME"

#
# Setup the paths
#
export WORK=$OLDATA/$NODENAME
export LOG=$WORK
export DATA=$WORK/consensus

# Force the directories to exist to handled recreating the directories
mkdir -p $DATA/config
mkdir -p $DATA/data

#
# Cleanup, but don't delete directories...
#
find $DATA -depth -name "*.wal" -type d -exec rm -r {} \;
find $WORK -depth -name "*.db" -type d -exec rm -r {} \;
find $WORK -type f -exec rm -f {} \;

#
# Control the working directory
#
pushd $WORK > /dev/null

#
# Cleanout any of the old database files
#
rm $LOG/*.log > /dev/null 2>&1

popd > /dev/null

