#!/bin/bash
#
# Reset our chain, remove any extra files and databases
#


if [ -z "$1" ]; then
	NODECOUNT=4
else
	NODECOUNT="$1"
fi

#
# Startup a bunch of nodes to act as a full block chain instance
#
export CMD=$OLSCRIPT
export STAGING=$OLDATA/staging

rm -rf $OLDATA/staging/*
#
# Generate the overall genesis and validator information
#
tendermint testnet --o $STAGING --v $NODECOUNT >> $OLDATA/tendermint.log

#
# Process the validators first
#
nodes="David-Node#node0 Alice-Node#node1 Bob-Node#node2 Carol-Node#node3"

for node in $nodes
do
	$CMD/resetValidator $node $STAGING
done

#
# Process any fullnodes that are watching
#
tendermint gen_node_key --home $OLDATA/staging/node4 >> $OLDATA/tendermint.log

$CMD/resetNode "Emma-Node#node4" $STAGING

