#!/bin/bash

#
# Reset the Bitcoin chain back to genesis
#

export CMD=$OLSCRIPT

export LOG=$OLDATA

$CMD/stopBitcoin

echo "============================================================" >> $LOG/bitcoin.log
echo "Clean all bitcoin data" >> $LOG/bitcoin.log
echo "Clean all bitcoin data"

rm -rf $OLDATA/bitcoin/*

mkdir -p $OLDATA/bitcoin/A
mkdir -p $OLDATA/bitcoin/B
mkdir -p $OLDATA/bitcoin/C

# Set a minimal block generation to insure that all accounts have balances 
echo "Preallocating Bitcoin Accounts"
$CMD/startBitcoin
sleep 4

bitcoin-cli -regtest -rpcuser=oltest01 -rpcpassword=olpass01 -rpcport=18831 generate 20 > /dev/null
sleep 1
bitcoin-cli -regtest -rpcuser=oltest02 -rpcpassword=olpass02 -rpcport=18832 generate 20 > /dev/null
sleep 1
bitcoin-cli -regtest -rpcuser=oltest03 -rpcpassword=olpass03 -rpcport=18833 generate 101 > /dev/null

$CMD/stopBitcoin

echo "Bitcoin data reset done"
