#!/bin/bash
#
# Reset our chain, remove any extra files and databases
#


if [ -z "$1" ]; then
	NODECOUNT="$1"
else
	NODECOUNT=3
fi

#
# Startup a bunch of nodes to act as a full block chain instance
#
export CMD=$OLSCRIPT

export STAGING=$OLDATA/staging

mkdir -p $STAGING

#
# Generate the overall genesis and validator information
#
tendermint testnet --home $STAGING --dir $STAGING --n $NODECOUNT

nodes="OneLedger-One#mach0 OneLedger-Two#mach1 OneLedger-Three#mach2"

for node in $nodes
do
	$CMD/resetNode $node $STAGING 
done

