#!/bin/sh
#
# Reset our chain, remove any extra files and databases
#

#set -eu

if [ -z "$1" ]; then
	export NODENAME="OneLedger-One"
else
	export NODENAME="$1"
fi

#
# Setup the paths
#
export WORK=$OLDATA/$NODENAME
export LOG=$WORK
export DATA=$WORK/tendermint

mkdir -p $DATA

# Control the working directory
pushd $WORK

#
# Cleanout any of the old database files
#

#
# Reset the main tendermint chain
#
tendermint unsafe_reset_all --home $DATA > $LOG/tendermint_init.log
tendermint init --home $DATA > $LOG/tendermint_init.log

#
# Reset our chain
#

#fullnode unsafe_reset_all > $LOG/fullnode_init.log
#fullnode init > $LOG/fullnode_init.log

#
# Reset Etheruem's chain
#

#
# Reset the Bitcoin chain
#

popd

