#!/bin/sh

#
# Startup a bunch of nodes to act as a full block chain instance
#
export CMD=$OLSCRIPT

setup="\
	OneLedger-One#127.0.0.1:46611 \
	OneLedger-Two#127.0.0.1:46612 \
	OneLedger-Three#127.0.0.1:46613 \
"
peers=""
for entry in $setup
do
	export name=`echo $entry | awk -F# '{ print $1 }'`
	export ip=`echo $entry | awk -F# '{ print $2 }'`

	key=`$CMD/enquireNode $name`

	if [ -z "$peers" ]
	then
		peers=$key@$ip
	else
		peers=$peers,$key@$ip
	fi
done

#peers="842bf7def90dcc955833909364c84fecca941316@127.0.0.1:46611,7e5d6fbd319877aa8de30680cd6fc45d1ca7a41d@127.0.0.1:46612,6e2ea713878f38838049072f412d9501e7cb47e6@127.0.0.1:46613"

local=tcp://127.0.0.1

nodes="\
	  OneLedger-One#$local:46601#$local:46611#$local:46621#$peers \
	  OneLedger-Two#$local:46602#$local:46612#$local:46622#$peers \
	OneLedger-Three#$local:46603#$local:46613#$local:46623#$peers \
"

for entry in $nodes 
do
	echo "------ STARTING $entry ------"
	$CMD/startNode $entry
	sleep 10
done
