#!/bin/bash

export CMD=$OLSCRIPT


if [ -z "$1" ]; then
	name="David"
else
	name=$1
fi

nodeName=`olconfig get -c $name -p NodeName`
#p2pAddress=`olconfig get -c $name -p P2PAddress`
#rpcAddress=`olconfig get -c $name -p RpcAddress`
#appAddress=`olconfig get -c $name -p AppAddress`
#peers=`olconfig get --peers -p Alice -p Bob`
peers=`olconfig get --peers -p Emma`
seeds=`olconfig get --seeds -p Emma`

export WORK=$OLDATA/$nodeName
export LOG=$WORK
export DATA=$WORK/consensus

pushd $WORK > /dev/null

pids=`pgrep -f "^olfullnode node -c $name.*"`

if [ -z "$pids" ]

then
	echo "============================================================" >> $LOG/olfullnode.log
	echo "Starting OLFullnode" >> $LOG/olfullnode.log
	echo "============================================================" >> $LOG/olfullnode.log


  olmonitor start olvm execute -c $name >>$LOG/olvm.log 2>&1 &
  
  olfullnode node -c $name\
		--root $WORK/olfullnode \
		--tendermintRoot $DATA \
		--seeds $seeds \
		--persistent_peers $peers \
		>> $LOG/olfullnode.log 2>&1 &

	echo "$nodeName has been started"
	sleep 3
else
	echo "OLFullnode $nodeName was already running"
fi

popd >> /dev/null
