#!/bin/bash

#
# Startup a bunch of nodes to act as a full block chain instance
#
export CMD=$OLSCRIPT

nodes="David Alice Bob Carol Emma"

for entry in $nodes
do
#	$CMD/testNode $entry
#	if [ $? -eq 0 ]; then
		$CMD/startNode $entry
#	fi
done
