#!/bin/bash

export CMD=$OLSCRIPT


if [ -z "$1" ]; then
	name="Admin"
else 
	name=$1
fi

if [ "$2" = "register" ]; then
	echo "Adding the Register Flag"
	extra="--register $name"
fi

echo "Starting $name"

prefix="tcp://127.0.0.1:"
nodeName=`$CMD/lookup $name NodeName`
p2pAddress=`$CMD/lookup $name P2PAddress $prefix`
rpcAddress=`$CMD/lookup $name RPCAddress $prefix`
appAddress=`$CMD/lookup $name AppAddress $prefix`

prefix="127.0.0.1:"
key=`$CMD/getNodeId $nodeName`
peers=`$CMD/lookup $name Peers $prefix $id`

#echo "nodeName=$nodeName"
#echo "p2pAddress=$p2pAddress"
#echo "rpcAddress=$rpcAddress"
#echo "appAddress=$appAddress"
#echo "peers=$peers"

export WORK=$OLDATA/$nodeName
export LOG=$WORK
export DATA=$WORK/tendermint

pushd $WORK > /dev/null

#
# Startup Tendermint consensus
#
pids=`pgrep -f "tendermint.*--home $DATA.*"`
if [ -z "$pids" ]

then
	echo "============================================================" >> $LOG/tendermint.log
	echo "Starting Tendermint" >> $LOG/tendermint.log
	echo "============================================================" >> $LOG/tendermint.log
	#tendermint node --proxy_app "unix://data.sock" >> $LOG/tendermint.log &
	tendermint node --home $DATA \
		--moniker $nodeName \
		--rpc.laddr $rpcAddress \
		--p2p.laddr $p2pAddress \
		--proxy_app $appAddress \
		--p2p.persistent_peers $peers \
		>> $LOG/tendermint.log 2>&1 &
else
	echo "Tendermint $nodeName is already running"
fi

#
# Startup Fullnode
#
pids=`pgrep -f "fullnode.*--node $nodeName.*"`
if [ -z "$pids" ]

then
	echo "============================================================" >> $LOG/fullnode.log
	echo "Starting Fullnode" >> $LOG/fullnode.log
	echo "============================================================" >> $LOG/fullnode.log
	fullnode node --node $nodeName --root $WORK/fullnode --address $appAddress $extra >> $LOG/fullnode.log 2>&1 &
	echo fullnode node --node $nodeName --root $WORK/fullnode --address $appAddress $extra 
else
	echo "Fullnode $nodeName is already running"
fi

#
# Startup Ethereum
#

#
# Startup Bitcoin
#
echo "$nodeName is Started"

popd >> /dev/null
