#!/bin/sh

#
# Startup a single node in our chain (tendermint for consensus and a fullnode validator)
#

#
# For now, use local dir but needs to be fixed
#
export CMD=$OLSCRIPT

export WORK=$OLDATA
export LOG=$OLDATA
export DATA=$OLDATA/tendermint

pushd $WORK > /dev/null

#
# Startup Tendermint consensus
#
pids=`pidof tendermint`
if [ -z $pids ]
then
	echo "============================================================" >> $LOG/tendermint.log
	echo "Starting Tendermint" >> $LOG/tendermint.log
	echo "============================================================" >> $LOG/tendermint.log
	#tendermint node --proxy_app "unix://data.sock" >> $LOG/tendermint.log &
	tendermint node --home $DATA >> $LOG/tendermint.log &
else
	echo "Tendermint is already running"
fi

#
# Startup Fullnode
#

pids=`pidof fullnode`
if [ -z $pids ]
then
	echo "============================================================" >> $LOG/fullnode.log
	echo "Starting Fullnode" >> $LOG/fullnode.log
	echo "============================================================" >> $LOG/fullnode.log
	fullnode node >> $LOG/fullnode.log &
else
	echo "Fullnode is already running"
fi

#
# Startup Ethereum
#

#
# Startup Bitcoin
#
echo "Everything is Started"

popd >> /dev/null
