#!/bin/sh

#
# Startup a bunch of nodes to act as a full block chain instance
#
export CMD=$OLSCRIPT

nodes="Admin Alice Bob Carol"

for entry in $nodes 
do
	echo "------ STARTING $entry ------"
	$CMD/startNode $entry
	sleep 3 
done
