#!/bin/sh

#
# Startup a bunch of nodes to act as a full block chain instance
#
export CMD=$OLSCRIPT

setup="\
	OneLedger-Admin#127.0.0.1:46611 \
	OneLedger-Alice#127.0.0.1:46612 \
	OneLedger-Bob#127.0.0.1:46613 \
	OneLedger-Carol#127.0.0.1:46614 \
"
peers=""
for entry in $setup
do
	export name=`echo $entry | awk -F# '{ print $1 }'`
	export ip=`echo $entry | awk -F# '{ print $2 }'`

	key=`$CMD/getNodeId $name`

	if [ -z "$peers" ]
	then
		peers=$key@$ip
	else
		peers=$peers,$key@$ip
	fi
done

local=tcp://127.0.0.1

nodes="\
	  OneLedger-Admin#$local:46601#$local:46611#$local:46621#$peers \
	  OneLedger-Alice#$local:46602#$local:46612#$local:46622#$peers \
	    OneLedger-Bob#$local:46603#$local:46613#$local:46623#$peers \
	  OneLedger-Carol#$local:46604#$local:46614#$local:46624#$peers \
"

for entry in $nodes 
do
	echo "------ STARTING $entry ------"
	$CMD/startNode $entry
	sleep 3 
done
