#!/bin/bash

#
# Startup a single node in our chain (tendermint for consensus and a olfullnode validator)
#

if [ -z "$1" ]; then
	export name="David-Node"
else
	export name=$1
fi

#
# For now, use local dir but needs to be fixed
#
nodeName=`olconfig get -c $name -p NodeName`
export CMD=$OLSCRIPT
export WORK=$OLDATA/$nodeName
export LOG=$WORK
export DATA=$WORK/tendermint

mkdir -p $DATA

pushd $WORK > /dev/null

#
# Stop Tendermint consensus
#
pids=`pgrep -f "tendermint.*--home $DATA.*"`
if ! [ -z "$pids" ]
then
	echo "============================================================" >> $LOG/tendermint.log
	echo "Stopping Tendermint" >> $LOG/tendermint.log
	echo "============================================================" >> $LOG/tendermint.log
	pkill -9 -f "tendermint.*--home $DATA.*" >> $LOG/tendermint.log
	killed=true
fi

#
# Stop OLFullnode
#
pids=`pgrep -f "olfullnode.*-c $name.*"`
if ! [ -z "$pids" ]
then
	echo "============================================================" >> $LOG/olfullnode.log
	echo "Stopping Fullnode" >> $LOG/olfullnode.log
	echo "============================================================" >> $LOG/olfullnode.log
	pkill -9 -f "olfullnode.*-c $name.*" >> $LOG/olfullnode.log
	killed=true
fi

pids=`pgrep -f "olmonitor start.*-c $name"`
if ! [ -z "$pids" ]
then
	pkill -9 -f "olmonitor start.*-c $name" >> $LOG/olvm.log
	killed=true
fi

pids=`pgrep -f "olvm execute -c $name"`
if ! [ -z "$pids" ]
then
	pkill -9 -f "olvm execute -c $name" >> $LOG/olvm.log
	killed=true
fi

if ! [ -z "$killed" ]
then
	echo "Stopped $nodeName"
fi

popd >> /dev/null
