#!/bin/bash

#
# Startup a single node in our chain (tendermint for consensus and a olfullnode validator)
#

if [ -z "$1" ]; then
	export name="David-Node"
else
	export name=$1
fi

#
# For now, use local dir but needs to be fixed
#
export CMD=$OLSCRIPT

nodeName=`$CMD/lookup $name NodeName`

export WORK=$OLDATA/$nodeName
export LOG=$WORK
export DATA=$WORK/tendermint

mkdir -p $DATA

pushd $WORK > /dev/null

echo "Stopping $nodeName"
#
# Stop Tendermint consensus
#

echo "============================================================" >> $LOG/tendermint.log
echo "Stopping Tendermint" >> $LOG/tendermint.log
echo "============================================================" >> $LOG/tendermint.log
pkill -f "tendermint.*--home $DATA.*" >> $LOG/tendermint.log

#
# Stop OLFullnode
#
echo "============================================================" >> $LOG/olfullnode.log
echo "Stopping OLFullnode" >> $LOG/olfullnode.log
echo "============================================================" >> $LOG/olfullnode.log
pkill -f "olfullnode.*--node $nodeName.*" >> $LOG/olfullnode.log

#
# Stop Ethereum
#

#
# Stop Bitcoin
#

popd >> /dev/null
