#!/bin/sh

#
# Startup a single node in our chain (tendermint for consensus and a fullnode validator)
#

if [ -z "$1" ]; then
	export NODENAME="OneLedger-One"
else
	export NODENAME=$1
fi

#
# For now, use local dir but needs to be fixed
#
export CMD=$OLSCRIPT

export WORK=$OLDATA/$NODENAME
export LOG=$WORK
export DATA=$WORK/tendermint

pushd $WORK > /dev/null

#
# Startup Tendermint consensus
#

echo "============================================================" >> $LOG/tendermint.log
echo "Stopping Tendermint" >> $LOG/tendermint.log
echo "============================================================" >> $LOG/tendermint.log
pidof -k tendermint >> $LOG/tendermint.log

#
# Startup Fullnode
#
echo "============================================================" >> $LOG/fullnode.log
echo "Stopping Fullnode" >> $LOG/fullnode.log
echo "============================================================" >> $LOG/fullnode.log
pidof -k fullnode >> $LOG/fullnode.log

#
# Startup Ethereum
#

#
# Startup Bitcoin
#

popd >> /dev/null
