#!/bin/bash

#
# Startup a single node in our chain (tendermint for consensus and a fullnode validator)
#

if [ -z "$1" ]; then
	export name="David-Node"
else
	export name=$1
fi

#
# For now, use local dir but needs to be fixed
#
export CMD=$OLSCRIPT

nodeName=`$CMD/lookup $name NodeName`

export WORK=$OLDATA/$nodeName
export LOG=$WORK
export DATA=$WORK/tendermint

mkdir -p $DATA

pushd $WORK > /dev/null

#
# Stop Tendermint consensus
#

pids=`pgrep -f "tendermint.*--home $DATA.*"`
if ! [ -z "$pids" ]
then
	echo "============================================================" >> $LOG/tendermint.log
	echo "Stopping Tendermint" >> $LOG/tendermint.log
	echo "============================================================" >> $LOG/tendermint.log
	pkill -f "tendermint.*--home $DATA.*" >> $LOG/tendermint.log
	killed=true
fi

#
# Stop Fullnode
#
pids=`pgrep -f "fullnode.*--node $nodeName.*"`
if ! [ -z "$pids" ]
then
	echo "============================================================" >> $LOG/fullnode.log
	echo "Stopping Fullnode" >> $LOG/fullnode.log
	echo "============================================================" >> $LOG/fullnode.log
	pkill -f "fullnode.*--node $nodeName.*" >> $LOG/fullnode.log
	killed=true
fi

if ! [ -z "$killed" ]
then
	echo "Stopped $nodeName"
fi

popd >> /dev/null
