---
- name: create a systemd olfullnode service file
  copy:
    dest: "/etc/systemd/system/olfullnode.service"
    owner: "root"
    group: "root"
    mode: 0644
    content: |
      [Unit]
      Description=olfullnode
      Wants=network-online.target
      After=network-online.target

      [Service]
      Type=simple
      #User=alertmanager
      #Group=alertmanager
      ExecStart=/root/go/bin/olfullnode node --root /opt/data/fullnode > /opt/data/fullnode/fullnode.log &

      #Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: enabling fullnode service
  command: systemctl enable olfullnode.service
  #when: systemd_service == "true"

- name: Start service olfullnode
  command: service olfullnode start

- name: git pull
  git:
    repo: https://github.com/Oneledger/protocol.git
    dest: /opt/protocol
    version: "master"
    refspec: '+refs/pull/*:refs/heads/*'
  tags: update

- name: compile binary
  shell: chdir=/opt/protocol make update install_c
  tags: update