---
- name: create a systemd olfullnode service file
  copy:
    dest: "/etc/systemd/system/olfullnode.service"
    owner: "root"
    group: "root"
    mode: 0644
    content: |
      [Unit]
      Description=olfullnode
      Wants=network-online.target
      After=network-online.target

      [Service]
      Type=simple
      #User=alertmanager
      #Group=alertmanager
      ExecStart=/root/go/bin/olfullnode node --root /opt/data/fullnode > /opt/data/fullnode/fullnode.log &

      #Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  tags: create

- name: enabling fullnode service
  command: systemctl enable olfullnode.service
  tags: create
  #when: systemd_service == "true"

- name: Start service olfullnode
  systemd:
    name: olfullnode.service
    scope: system
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: create

- name: stopping fullnode
  command: pkill olfullnode
  tags: update

- name: Deleting protocol directory
  file:
    path: /opt/protocol
    state: absent
  tags: update

- name: git clone
  git:
    repo: https://{{git_token}}@github.com/Oneledger/protocol.git
    dest: /opt/protocol
    version: "{{version}}"
    refspec: '+refs/pull/*:refs/heads/*'
  tags: update

- name: compile binary
  shell: chdir=/opt/protocol make update install_c
  tags: update

- name: starting fullnode
  command: chdir=/opt/data/fullnode ./start.sh
  tags: update
