# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

 required = ["github.com/mattn/go-isatty",  "github.com/pkg/errors" ]

#[[constraint]]
#  name = "golang.org/x/net"
#  version = "release-branch.go1.9"

# [[constraint]]
#   name = "github.com/golang/protobuf"
#   version = "~1.0.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.13.0"

# TM 0.23.1 is tied to this version of /x/net
[[constraint]]
  name = "golang.org/x/net"
  revision = "292b43bbf7cb8d35ddf40f8d5100ef3837cced3f"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "~0.0.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"
#  version = "0.0.2"
#
#[[constraint]]
#  name = "github.com/tendermint/abci"
#  version = "~0.12.0"

#[[constraint]]
#  name = "github.com/tendermint/go-crypto"
#  version = "~0.6.2"

[[constraint]]
  name = "github.com/tendermint/go-amino"
  version = "=0.10.1"

# TODO: Change this to a constraint, set to override b/c iavl 0.10.0 has a version dependency on tendermint 0.22.0
[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=0.23.1"

[[constraint]]
  name = "github.com/tendermint/iavl"
  version = "=0.10.0"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"

[[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    non-go = false
    unused-packages = false

[prune]
  go-tests = true
  unused-packages = true

