---
apiVersion: v1
kind: Service
metadata:
  name: fullnode-service
  labels:
    run: fullnode-service
spec:
  ports:
  - name: sdk-port
    port: 56606
    targetPort: sdk-port
    protocol: TCP
  - name: rpc-port
    port: 56604
    targetPort: rpc-port
    protocol: TCP  
  type: NodePort
  selector:
    app: fullnode