apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullnode-deployment
  labels:
    app: fullnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullnode
  template:  
    metadata:
      labels:
        app: fullnode
    spec:
      volumes:
      - name: fullnode-pv-claim
        persistentVolumeClaim:
          claimName: fullnode-pv-claim
      containers:
      - name: fullnode-container
        image: gcr.io/atomic-land-223022/oneledger/chronos:v0.10.0
        volumeMounts:
          - mountPath: "/home/node/go/data"
            name: fullnode-pv-claim
        ports:
          - name: sdk-port
            containerPort: 26606
            protocol: TCP
          - name: rpc-port
            containerPort: 26604
            protocol: TCP
      initContainers:
      - name: change-persistent-data-ownership 
        image: gcr.io/atomic-land-223022/oneledger/chronos:v0.10.0
        securityContext:
          runAsUser: 0
        command:
        - chown
        args:
        - -R  
        - node:node
        - /home/node/go/data 
        volumeMounts:
        - name: fullnode-pv-claim
          mountPath: "/home/node/go/data"