apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-postgres
  template:  
    metadata:
      labels:
        app: explorer-postgres
    spec:
      volumes:
      - name: psql-pv-claim
        persistentVolumeClaim:
          claimName: psql-pv-claim
      containers:
      - name: postgres-database
        image: gcr.io/atomic-land-223022/oneledger/explorer_postgres:latest
        imagePullPolicy: "Always"
        ports: 
        - name: psql-port
          containerPort: 5432
          protocol: TCP 
        volumeMounts:
        - mountPath: /data
          name: psql-pv-claim
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          exec:
            command:
            - psql
            - -U
            - postgres 
            - -h 
            - localhost 
            - -d 
            - explorer_chronos
            - -c 
            - "SELECT 1 FROM blockchain.blocks"
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
      initContainers:
      - name: change-persistent-data-ownership 
        image: gcr.io/atomic-land-223022/oneledger/explorer_postgres:latest
        imagePullPolicy: "Always"
        securityContext:
          runAsUser: 0
        command:
        - chown
        args:
        - -R  
        - postgres:postgres
        - /data
        volumeMounts:
        - mountPath: /data
          name: psql-pv-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: psql-pv-claim
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: psql-service
  labels:
    run: psql-service
    app: explorer
spec:
  ports:
  - name: psql-port
    port: 5432
    targetPort: psql-port
    protocol: TCP
  type: NodePort
  selector:
    app: explorer-postgres