#!/bin/bash
# find node folder from docker inspect result
node_folder=$(docker inspect 0-Node | sed -n 's/^.*"Source"\: "\(.*\)\/[0-9]-Node.*$/\1/p')
name=$(ls -l $node_folder | grep Node | awk '(NR==1){print $9}')
echo "run list validator set test command on node $name"
# shellcheck disable=SC2070

cnt=$(python $OLROOT/protocol/DOCKER-network/dockernet run $name "olclient validatorset | grep "^Address" | wc -l" | tr -d '\r')
echo $cnt
if [ $cnt -ne 4 ]
then
    echo "Validator test failed, only $cnt validators"
    exit  -1
fi
echo "validator test success"
