#!/bin/bash

for name in $(ls -l $OLDATA/devnet | awk '(NR >3 && NR < 5){print $9}')
do
    echo "start loadtest on node: $name"
    time olclient loadtest --root $OLDATA/devnet/$name --threads 10 --interval 5 --max-tx 200000 #>> /dev/null &
    sleep 1
done

c=0
while [ $c -lt 4 ]
do
    sleep 10
    name=$(ls -l $OLDATA/devnet | awk '(NR==4){print $9}')
    c=$(grep Loadtest $OLDATA/devnet/$name/olfullnode.log | wc -l )
done

grep Loadtest $OLDATA/devnet/$name/olfullnode.log

sleep 1
