#!/bin/bash

for name in $(ls -l $OLDATA/devnet | awk '(NR>3){print $9}')
do
    echo "start loadtest on node: $name"
    olclient loadtest --root $OLDATA/devnet/$name --threads 3 --interval 1 --max-tx 100000 >> /dev/null &
    sleep 1
done

c=0
while [ $c -lt 3 ]
do
    name=$(ls -l $OLDATA/devnet | awk '(NR==2){print $9}')
    c=$(grep Loadtest $OLDATA/devnet/$name/olfullnode.log | wc -l )
    sleep 10
done

grep Loadtest $OLDATA/devnet/$name/olfullnode.log

sleep 1