#!/bin/bash

echo

rm -rf $OLDATA/devnet/*

olfullnode init devnet --dir $OLDATA/devnet --nonvalidators 1 \
--eth_rpc  HTTP://127.0.0.1:7545 \
#--deploy_smart_contracts \
#--cloud_deploy \

#--deploy_eth_contract HTTP://127.0.0.1:7545 \

  # --empty_blocks

