#!/bin/bash

echo

rm -rf $OLDATA/devnet/*

olfullnode init devnet --dir $OLDATA/devnet --nonvalidators 1 \
--empty_blocks \
--loglevel 4 \
--eth_rpc HTTP://127.0.0.1:7545 \
#--deploy_smart_contracts \

#--eth_rpc https://rinkeby.infura.io/v3 \
#--eth_rpc HTTP://127.0.0.1:7545 \
