#!/bin/bash

echo


echo

rm -rf $OLDATA/devnet/*

olfullnode init devnet --dir $OLDATA/devnet --validators 4 --nonvalidators 1 \
#--eth_rpc HTTP://127.0.0.1:7545 \
#--deploy_smart_contracts \
#--empty_blocks \
#--loglevel 4 \
#--cloud_deploy \




#"46c6cd6cb4dbb9675c8c1ff693f62918930d3a35@34.70.164.191"


#olfullnode init devnet --dir $OLDATA/devnet --nonvalidators 1 \
##--eth_rpc HTTP://127.0.0.1:7545 \
##--deploy_smart_contracts \
##--empty_blocks \
##--loglevel 4 \
##--cloud_deploy \
##
##https://rinkeby.infura.io/v3 \
