#!/bin/bash

for name in $(ls -l $OLDATA/devnet | grep Node  | awk '(NR>0){print $9}')
do
    echo "Saving Data From Node: $name"
    olfullnode save_state --root $OLDATA/devnet/$name --filename genesis.json --outDir $OLDATA/devnet/$name/consensus/config/

    echo "Deleting Node Data"
    rm -rf $OLDATA/devnet/$name/nodedata/*
    rm -rf $OLDATA/devnet/$name/consensus/data/*.db
    rm -rf $OLDATA/devnet/$name/consensus/data/*.wal
    rm -rf $OLDATA/devnet/$name/consensus/config/addrbook.json

cat > $OLDATA/devnet/$name/consensus/data/priv_validator_state.json <<EOF
{
"height": "0",
"round": "0",
"step": 0
}
EOF

done
