#!/bin/bash

for name in $(ls -l $OLDATA/mainnet | grep Node  | awk '(NR>0){print $9}')
do
    echo "Start Node: $name"
    olfullnode node --root $OLDATA/mainnet/$name >> $OLDATA/mainnet/$name/olfullnode.log 2>&1  &
    sleep 1
done

sleep 3
