#!/bin/bash

RED='\e[31m'
GRN="\e[32m"
YEL="\e[33m"
NC='\033[0m'

# use 0-Node to test
name=$(ls -l $OLDATA/devnet | grep Node | awk '(NR==1){print $9}')
if [ -z "$name" ]; then
    echo -e "${RED}failed to find a test node${NC}"
fi
root_dir=$OLDATA/devnet/$name
echo "run purge validator test command on node $name"

# how many validators we have
cnt_before=$(olclient validatorset --root $root_dir | grep "^Address" | wc -l )

# create a test admin account
addr_admin=$(olclient account --root $root_dir add --name admin --password admin | grep Address | awk '{print $NF}' | cut -d'x' -f 2)
if [ $? -ne 0 ]; then
    echo -e "${RED}failed to create admin account${NC}"
    exit -1
fi
echo "admin address: $addr_admin"

# find an initial token holder address
addr_holder=$(olclient list --root $root_dir | grep Address | awk 'END{print $2}' | cut -d'x' -f 2)
if [ $? -ne 0 ]; then
    echo -e "${RED}failed to get token holder address${NC}"
    exit -1
fi
echo "holder address: $addr_holder"

# send fund from token holder to admin
olclient sendfunds --root $root_dir --party $addr_holder --counterparty $addr_admin --amount 100 --fee 1
if [ $? -ne 0 ]; then
    echo -e "${RED}sending fund from $addr_holder to $addr_admin failed${NC}"
    exit -1
fi

# get last validator's address to purge
addr_validator=$(olclient validatorset --root $root_dir | grep '^Address' | awk 'END{print $NF}' | cut -d'x' -f 2)
if [ $? -ne 0 ]; then
    echo -e "${RED}failed to get a validator address${NC}"
    exit -1
fi

# purge this validator
echo "purging validator: $addr_validator"
olclient purgevalidator --root $root_dir --admin $addr_admin --validator $addr_validator --password admin
if [ $? -ne 0 ]; then
    echo -e "${RED}failed to purge validator: 0x$addr_validator${NC}"
    exit -1
fi

# check how many validators left after purging
cnt_after=$(olclient validatorset --root $root_dir | grep "^Address" | wc -l )
if [ $cnt_after -ne $((cnt_before-1)) ]; then
    echo -e "${RED}failed to purge validator, cnt_before: $cnt_before, cnt_after: $cnt_after${NC}"
    exit  -1
fi

echo -e "${GRN}testpurgeValidator completed successfully${NC}"
