#!/bin/bash

name=$(ls -l $OLDATA/devnet | grep Node  | awk '(NR==1){print $9}')

if [ -n $name ]
then
    echo "run load test command on node $name"
    olclient loadtest --root $OLDATA/devnet/$name --threads 2 --interval 10 --max-tx 20

fi

sleep 5

