#!/bin/bash

name=$(ls -l $OLDATA/devnet | grep Node  | awk '(NR==1){print $9}')

# shellcheck disable=SC2070
if [ -n "$name" ]
then
    echo "run sendPool Test $name"
    olclient sendpooltest --root $OLDATA/devnet/$name --threads 1 --interval 10 --max-tx 20

fi

sleep 5

