#!/bin/bash


name=$(ls -l $OLDATA/devnet | grep Node | awk '(NR==5){print $9}')

if [ -n $name ]
then
    echo "run applyvalidator test command on node $name"
    olclient applyvalidator --root $OLDATA/devnet/$name --amount 1
    sleep 1
fi

