services:
  builder:
    command: bash -c "rm -rf /opt/data/devnet/*-Node && cd /home/ubuntu/go/protocol
      && make install_c && olfullnode init devnet --dir /opt/data/devnet --eth_rpc
      https://rinkeby.infura.io/v3 --validators 4 --voting_deadline 12 --subnet \"10.5.0.0/16\"
      --maturity_time 4 --nonvalidators 1 --total_funds 1000000000 --funding_deadline
      10 --deleg_rewards_maturity_time 4 --loglevel 4 --timeout_commit 1000 --docker
      --rewards_interval 1 && /bin/bash"
    container_name: builder
    image: olprotocol
    ports:
    - 443:443
    - 8080:8080
    stdin_open: true
    tty: true
    volumes:
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/src/github.com/Oneledger/protocol:/home/ubuntu/go/protocol
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockerbin:/home/ubuntu/go/bin
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockertest:/opt/data/devnet
version: '3'
