version: "3"

services:
  0-Node:
    container_name: 0-Node
    image: olprotocol
    ports:
      - "26602:26602"
    volumes:
      - ~/oldata/docker/bin:/home/ubuntu/go/bin
      - ~/oldata/docker/0-Node:/opt/data/devnet
    command: >
      bash -c "cd /opt/data/devnet &&
              olfullnode node --root /opt/data/devnet >> /opt/data/devnet/olfullnode.log 2>&1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10
    stdin_open: true
    tty: true

  1-Node:
    container_name: 1-Node
    image: olprotocol
    volumes:
      - ~/oldata/docker/bin:/home/ubuntu/go/bin
      - ~/oldata/docker/1-Node:/opt/data/devnet
    command: >
      bash -c "cd /opt/data/devnet &&
              olfullnode node --root /opt/data/devnet >> /opt/data/devnet/olfullnode.log 2>&1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11
    stdin_open: true
    tty: true

  2-Node:
    container_name: 2-Node
    image: olprotocol
    volumes:
      - ~/oldata/docker/bin:/home/ubuntu/go/bin
      - ~/oldata/docker/2-Node:/opt/data/devnet
    command: >
      bash -c "cd /opt/data/devnet &&
              olfullnode node --root /opt/data/devnet >> /opt/data/devnet/olfullnode.log 2>&1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.12
    stdin_open: true
    tty: true

  3-Node:
    container_name: 3-Node
    image: olprotocol
    volumes:
      - ~/oldata/docker/bin:/home/ubuntu/go/bin
      - ~/oldata/docker/3-Node:/opt/data/devnet
    command: >
      bash -c "cd /opt/data/devnet &&
              olfullnode node --root /opt/data/devnet >> /opt/data/devnet/olfullnode.log 2>&1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.13
    stdin_open: true
    tty: true

  4-Node:
    container_name: 4-Node
    image: olprotocol
    volumes:
      - ~/oldata/docker/bin:/home/ubuntu/go/bin
      - ~/oldata/docker/4-Node:/opt/data/devnet
    command: >
      bash -c "cd /opt/data/devnet &&
              olfullnode node --root /opt/data/devnet >> /opt/data/devnet/olfullnode.log 2>&1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.14
    stdin_open: true
    tty: true

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

