networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
services:
  0-Node:
    command: bash -c "cd /opt/data/devnet && olfullnode node --root /opt/data/devnet
      >> /opt/data/devnet/olfullnode.log 2>&1"
    container_name: 0-Node
    image: olprotocol
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10
    ports:
    - 26600:26600
    - 26601:26601
    - 26602:26602
    stdin_open: true
    tty: true
    volumes:
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockerbin:/home/ubuntu/go/bin
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockertest/0-Node:/opt/data/devnet
  1-Node:
    command: bash -c "cd /opt/data/devnet && olfullnode node --root /opt/data/devnet
      >> /opt/data/devnet/olfullnode.log 2>&1"
    container_name: 1-Node
    image: olprotocol
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11
    ports:
    - 26603:26603
    - 26604:26604
    - 26605:26605
    stdin_open: true
    tty: true
    volumes:
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockerbin:/home/ubuntu/go/bin
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockertest/1-Node:/opt/data/devnet
  2-Node:
    command: bash -c "cd /opt/data/devnet && olfullnode node --root /opt/data/devnet
      >> /opt/data/devnet/olfullnode.log 2>&1"
    container_name: 2-Node
    image: olprotocol
    networks:
      vpcbr:
        ipv4_address: 10.5.0.12
    ports:
    - 26606:26606
    - 26607:26607
    - 26608:26608
    stdin_open: true
    tty: true
    volumes:
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockerbin:/home/ubuntu/go/bin
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockertest/2-Node:/opt/data/devnet
  3-Node:
    command: bash -c "cd /opt/data/devnet && olfullnode node --root /opt/data/devnet
      >> /opt/data/devnet/olfullnode.log 2>&1"
    container_name: 3-Node
    image: olprotocol
    networks:
      vpcbr:
        ipv4_address: 10.5.0.13
    ports:
    - 26609:26609
    - 26610:26610
    - 26611:26611
    stdin_open: true
    tty: true
    volumes:
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockerbin:/home/ubuntu/go/bin
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockertest/3-Node:/opt/data/devnet
  4-Node:
    command: bash -c "cd /opt/data/devnet && olfullnode node --root /opt/data/devnet
      >> /opt/data/devnet/olfullnode.log 2>&1"
    container_name: 4-Node
    image: olprotocol
    networks:
      vpcbr:
        ipv4_address: 10.5.0.14
    ports:
    - 26612:26612
    - 26613:26613
    - 26614:26614
    stdin_open: true
    tty: true
    volumes:
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockerbin:/home/ubuntu/go/bin
    - /Users/kerbals/Documents/mystuff/code/golang/mygocode/test/dockertest/4-Node:/opt/data/devnet
version: '3'
