- hosts: validator_node
  vars:
    uuid: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
  remote_user: steven
  tasks:
  - name: Include global variables
    include_vars:
      file: variables.yml
      name: config
  - name: create init.sh for token transaction
    copy:
      dest: "{{config.GOPATH}}/init.sh"
      content: |
        #!/bin/bash
        olclient update --root {{config.GOPATH}} --account "{{uuid}}-Oneledger"
        olclient testmint --root {{config.GOPATH}} --party "{{uuid}}-Oneledger" --amount "14210.23" --currency OLT
        sleep 1
        olclient register --root {{config.GOPATH}} --identity "{{uuid}}" --account "{{uuid}}-Oneledger" --node "{{uuid}}-Node" --fee 0.1
      mode: 511
  - name: execute init.sh script
    command: "/bin/bash {{config.GOPATH}}/init.sh"
    register: account_init_result
  - debug: "msg={{account_init_result.stdout_lines}}"