---
- hosts: all
  remote_user: "{{ssh_user}}"
  become: true
  become_user: root
  vars:
    GOPATH: /home/{{ssh_user}}/go
    OLROOT: "/home/{{ssh_user}}"
    GOLANG_INSTALL_DIR: /usr/local/go
    OLDATA: "{{GOPATH}}/data"
  roles:
    - role: gantsign.golang
      golang_gopath: "{{GOPATH}}"
      golang_version: 1.11.6
      golang_install_dir: "{{GOLANG_INSTALL_DIR}}"
  tasks:
  - name: Install a list of dependent packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - libleveldb-dev
      - libsnappy-dev
      - git
      - nano
      - python-pip
      - unzip
  - name: pull protocol repo 
    git:
      dest: "{{OLROOT}}/protocol"
      repo: https://github.com/Oneledger/protocol.git
      accept_hostkey: yes 
      force: yes
  - name: copy local private keys to remote for clone git private repo
    copy:
      src: "~/{{item}}"
      dest: "{{OLROOT}}/{{item}}"
      owner: "{{ssh_user}}"
      group: "{{ssh_user}}"
      mode: 0600
    with_items: 
      - .ssh/id_rsa
      - .ssh/id_rsa.pub  
  - name: pull protocol repo 
    git:
      dest: "{{OLROOT}}/infrastructure"
      repo: git@github.com:Oneledger/infrastructure.git
      key_file: "{{OLROOT}}/.ssh/id_rsa"
      accept_hostkey: yes 
      force: yes
  - name: change protocol repo ownership
    file:
      path: "{{OLROOT}}"
      owner: "{{ssh_user}}"
      group: "{{ssh_user}}"
      mode: '0744'
      recurse: true   
  - name: install ansible module
    pip:
      name: ansible>=2.8.0
  - name: install terraform executable 
    get_url:
      url: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      dest: "{{GOPATH}}"
      mode: 0744
  - name: Extract terraform into /usr/local/bin
    unarchive:
      src: "{{GOPATH}}/terraform_0.11.13_linux_amd64.zip"
      remote_src: true
      dest: /usr/local/bin
      mode: 711
  - name: set environment variable 
    lineinfile:
      path: /home/{{ssh_user}}/.bashrc
      line: "{{item}}"
      insertbefore: BOF
    with_items:
      - "export GOPATH={{GOPATH}}"
      - "export OLROOT={{OLROOT}}"
      - "export OLDATA={{OLDATA}}"
      - "export OLSCRIPT={{OLROOT}}/protocol/node/scripts"
      - "export OLSETUP={{OLROOT}}/protocol/node/setup"
      - "export OLTEST={{OLROOT}}/protocol/node/tests"
      - "export GO111MODULE=on"
      - "export PATH=$PATH:{{GOPATH}}/bin"
  - name: source bashrc 
    shell: . /home/{{ssh_user}}/.bashrc

    