- hosts: localhost
  connection: local
  vars:
    new_app_user: node
    validator_count: "{{vcount | default(4)}}"
  tasks:
  - name: run terraform apply 
    terraform:
      project_path: '../gcp/initialize-network'
      lock : true
      force_init: true  
      backend_config:
        key: "{{ stage | default('devnet') }}"
      variables: 
        name: "{{ stage | default('devnet') }}"
        vpc_ip_range: "{{ vpc_ip_range | default('10.10.0.0/20') }}"
        vmcount: "{{ node_count | default(5) }}"
        vm_machine_type: "{{ machine_type | default('n1-standard-1')}}"
        gce_ssh_user: "{{ remote_user | default('steven') }}"
        gce_ssh_pub_key_file: "{{ ssh_pub_key_file | default('~/.ssh/id_rsa.pub') }}"
    register: vm_data
  - set_fact: remote_hosts={{vm_data.outputs.public_ip.value}}
  - name: add knowm hosts 
    shell: ssh-keyscan -H {{item}} >> ~/.ssh/known_hosts
    loop: "{{remote_hosts}}"
  - name: add host to inventory file in memory 
    add_host:
      hostname: "{{item}}"
    loop: "{{remote_hosts}}"
  - name: add first 4 hosts to validator_node group 
    add_host:
      hostname: "{{item.1}}"
      group: "validator_node" 
      node_name: "{{item.0}}-Node"
      app_user: "{{new_app_user}}"
      APP_HOME: "/home/{{new_app_user}}/.olfullnode"
      remote_user: "{{ remote_user | default('steven') }}"
    with_indexed_items: "{{remote_hosts}}"
    when: item.0 < {{validator_count}}
  - name: add hosts after 4th host to seed_node group 
    add_host:
      hostname: "{{item.1}}"
      group: "seed_node"
      node_name: "{{item.0}}-Seed"
      app_user: "{{new_app_user}}"
      APP_HOME: "/home/{{new_app_user}}/.olfullnode"
      remote_user: "{{ remote_user | default('steven') }}"
    with_indexed_items: "{{remote_hosts}}"
    when: item.0 >= {{validator_count}}     
  - name: find Node data files to be deleted
    find:
      paths: "{{lookup('env','OLDATA')}}"
      patterns: '*-Node'
      file_type: directory
    register: files_to_delete
  - name: delete data files generated during fulltest
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
  - name: create consensus/ initialized network with dir
    shell: chdir={{lookup('env','OLDATA')}} olfullnode init devnet --root {{lookup('env','OLDATA')}} --validators {{validator_count}}