- hosts: localhost
  connection: local
  tasks:
  - name: setup the dependencies
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make tools update
  - name: compile the app binary artifact
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make install
  - name: run test integration test
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make fulltest
  - name: create consensus folder
    command: chdir={{lookup('env','OLROOT')}}/protocol olfullnode init --genesis genesis.json