- hosts: localhost
  connection: local
  tasks:
  - name: run terraform apply 
    terraform:
      project_path: '../gcp'
      lock : true
      force_init: true  
      backend_config:
        key: "{{ stage | default('devnet') }}"
      variables: 
        name: "{{ stage | default('devnet') }}"
        vpc_ip_range: "{{ vpc_ip_range | default('10.10.0.0/20') }}"
        vmcount: "{{ node_count | default(5) }}"
    register: vm_data
  - set_fact: remote_hosts={{vm_data.outputs.public_ip.value}}
  - name: add knowm hosts 
    shell: ssh-keyscan -H {{item}} >> ~/.ssh/known_hosts
    loop: "{{remote_hosts}}"
  - name: add host to inventory file in memory 
    add_host:
      hostname: "{{item}}"
    loop: "{{remote_hosts}}"
  - name: add first 4 hosts to validator_node group 
    add_host:
      name: "{{item.1}}"
      group: "validator_node" 
      app_user: node
      remote_user: "{{ remote_user | default('steven') }}"
    with_indexed_items: "{{remote_hosts}}"
    when: item.0 < 4
  - name: add hosts after 4th host to seed_node group 
    add_host:
      name: "{{item.1}}"
      group: "seed_node"
      node_name: consensus
      app_user: node
      remote_user: "{{ remote_user | default('steven') }}"
    with_indexed_items: "{{remote_hosts}}"
    when: item.0 >= 4 

  - name: specify alice-node 
    add_host: 
      name: "{{item.1}}"
      node_name: Alice-Node
    with_indexed_items: "{{remote_hosts}}"
    when: item.0 == 0 
  - name: specify Bob-node 
    add_host: 
      name: "{{item.1}}"
      node_name: Bob-Node
    with_indexed_items: "{{remote_hosts}}"
    when: item.0 == 1
  - name: specify David-node 
    add_host: 
      name: "{{item.1}}"
      node_name: David-Node
    with_indexed_items: "{{remote_hosts}}"
    when: item.0 == 2 
  - name: specify Carol-node 
    add_host: 
      name: "{{item.1}}"
      node_name: Carol-Node
    with_indexed_items: "{{remote_hosts}}"
    when: item.0 == 3 
    
  - name: find Node data files to be deleted
    find:
      paths: "{{lookup('env','OLDATA')}}"
      patterns: '*-Node'
      file_type: directory
    register: files_to_delete
  - name: delete data files generated during fulltest
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"

  - name: create temp config.toml file
    copy:
      content: ""
      dest: "{{lookup('env','OLDATA')}}/config.toml"
      force: yes
      mode: 0644
  - name: create consensus/ initialized network with dir
    shell: chdir={{lookup('env','OLDATA')}} olfullnode init devnet --root {{lookup('env','OLDATA')}}