- hosts: localhost
  connection: local
  tasks:
  - name: setup the dependencies
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make tools update
  - name: compile the app binary artifact
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make install
  - name: run test integration test
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make fulltest
  - name: display genesis file
    command: chdir={{lookup('env','GOPATH')}}/test cat ./Alice-Node/consensus/config/genesis.json
  - name: create temp config.toml file
    file:
      path: "{{lookup('env','GOPATH')}}/test"
      state: touch
      mode: 0644
  - name: change genesis file permission
    file:
      path: "{{lookup('env','GOPATH')}}/test/Alice-Node/consensus/config/genesis.json"
      mode: 0644
  - name: create consensus folder with dir
    command: chdir={{lookup('env','GOPATH')}}/test olfullnode init --genesis ./Alice-Node/consensus/config/genesis.json --dir {{lookup('env','GOPATH')}}/test