- hosts: localhost
  connection: local
  tasks:
  - name: setup the dependencies
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make update
  - name: compile the app binary artifact
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make install
  - name: run test integration test
    shell: chdir={{lookup('env','OLROOT')}}/protocol/node make fulltest
  - name: create temp config.toml file
    copy:
      content: ""
      dest: "{{lookup('env','GOPATH')}}/test/config.toml"
      force: yes
      mode: 0644
  - name: create consensus folder with dir
    command: chdir={{lookup('env','GOPATH')}}/test olfullnode init --genesis ./Alice-Node/consensus/config/genesis.json --dir {{lookup('env','GOPATH')}}/test