---
- hosts: all
  remote_user: steven
  become: true
  become_user: root
  vars:
    GOPATH: /home/{{app_user}}/go
    OLROOT: "{{GOPATH}}/src/github.com/Oneledger"
    GOLANG_INSTALL_DIR: /usr/local/go
  roles:
    - role: fullnode
      logging: "{{ enable_logging | default('false') }}"
      dev_mode: "{{ dev_env | default('false') }}"
      app_version: "{{ app_version | default('master') }}"
      systemd_service: "{{ systemd_service | default('false') }}"
  environment:
    GOPATH: "{{GOPATH}}"
    OLTEST: "{{OLROOT}}/protocol/node/tests"
    OLDATA: "{{OLDATA}}"
    OLSETUP: "{{OLROOT}}/protocol/node/setup"
    OLSCRIPT: "{{OLROOT}}/protocol/node/scripts"
    OLROOT: "{{OLROOT}}"
    PATH: "{{lookup('env', 'PATH')}}:/{{GOPATH}}/bin:{{GOLANG_INSTALL_DIR}}/bin"