- hosts: localhost
  connection: local
  vars:
    code_change: "{{recompile | default('true')}}"
  tasks:
  - name: add host
    add_host:
      name: "{{ ip }}"
      groups: fullnode
      app_user: "{{user | default('node') }}"
  - name: setup the dependencies
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make tools update
    when: code_change == 'true'
  - name: compile the app binary artifact
    command: chdir={{lookup('env','OLROOT')}}/protocol/node make install
    when: code_change == 'true'
  - name: create consensus folder
    command: chdir=../ olfullnode init --genesis genesis.json