# stop app processess running on validator and seed nodes
- hosts: all
  remote_user: lan
  become: true
  become_user: root
  tasks:
    - include: TerminateProcess.yml
      with_items:
        - olmonitor
        - olvm
        - olfullnode
      loop_control:
        loop_var: process
