- hosts: validator_node
  vars:
    uuid: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
  remote_user: "{{remote_user}}"
  become: true
  become_user: root
  tasks:
  - name: create init.sh for token transaction
    copy:
      dest: "{{APP_HOME}}/init.sh"
      content: |
        #!/bin/bash
        olclient update --root {{APP_HOME}} --account "{{uuid}}-Oneledger" 
      mode: 511
      owner: "{{app_user}}"
      group: "{{app_user}}"
  - name: execute init.sh script
    command: "/bin/bash {{APP_HOME}}/init.sh"
    register: account_init_result
  - debug: "msg={{account_init_result.stdout_lines}}"