- hosts: validator_node
  vars:
    uuid: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
    APP_HOME: "/home/{{app_user}}/go"
  remote_user: steven
  become: true
  become_user: root
  tasks:
  - name: create init.sh for token transaction
    copy:
      dest: "{{APP_HOME}}/init.sh"
      content: |
        #!/bin/bash
        olclient update --root {{APP_HOME}} --account "{{uuid}}-Oneledger"
        olclient testmint --root {{APP_HOME}} --party "{{uuid}}-Oneledger" --amount "14210.23" --currency OLT
        sleep 1
        olclient register --root {{APP_HOME}} --identity "{{uuid}}" --account "{{uuid}}-Oneledger" --node "{{uuid}}-Node" --fee 0.1
      mode: 511
      owner: "{{app_user}}"
      group: "{{app_user}}"
  - name: execute init.sh script
    command: "/bin/bash {{APP_HOME}}/init.sh"
    register: account_init_result
  - debug: "msg={{account_init_result.stdout_lines}}"