---
# tasks file for logstash
- name: install java and other dependency for logstash
  apt:
    name: ["default-jre", "apt-transport-https"] 
    update_cache: yes
- name: download public signing key for logstash
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
- name: Save the repository definition to /etc/apt/sources.list.d/elastic-7.x.list
  apt_repository: 
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main' 
    state: present 
    filename: /etc/apt/sources.list.d/elastic-7.x.list 
    update_cache: yes
- name: install logstash
  apt:
    name: logstash
    update_cache: yes
- name: install logstash journald plugin
  shell: /usr/share/logstash/bin/logstash-plugin install logstash-input-journald
- name: add logstash configuration file
  notify: restart logstash
  copy:
    dest: /etc/logstash/conf.d/journald_filter.conf
    mode: 0744
    owner: "root"
    group: "root" 
    content: |
        input {
            journald {
                lowercase => true
                seekto => "tail"
                thisboot => true
                type => "systemd"
                path => "/var/run/log/journal"
            }
        }
        filter {
            mutate {
                rename => ["_uid","id"]
            }
        }
        output {
            elasticsearch { 
                hosts => {{ elasticsearch_hosts | to_json }}
            }
        }    
- name: create serviced file for logstash
  notify: restart logstash
  copy:
    dest: /etc/systemd/system/logstash.service
    mode: 0744
    owner: "root"
    group: "root" 
    content: |
        [Unit]
        Description=logstash
        After=network.target

        [Service]
        User=root
        ExecStart=/usr/share/logstash/bin/logstash "--path.settings" "/etc/logstash"
        Restart=always
        [Install]
        WantedBy=multi-user.target
