[validators]
104.154.155.237
104.197.230.119
52.86.42.62 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/mani/Downloads/awskeypair.pem

[seed]
35.222.135.83

[sentry]
35.193.180.62
    
[fullnode]
54.157.163.8  ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/mani/Downloads/awskeypair.pem